name: InvisibleBarrier
main: Barrier\InvisibleBarrier
api: 3.0.0, 4.0.0
author: IceCruelStuff
version: 1.0.0
load: STARTUP
description: Adds invisible barriers to your server
website: https://github.com/IceCruelStuff/InvisibleBarrier
